(require 'python)
;(require 'python-mode)
(add-to-list 'auto-mode-alist '("\\.py\\'" . python-mode))
;; Initialize Pymacs
(autoload 'pymacs-apply "pymacs")
(autoload 'pymacs-call "pymacs")
(autoload 'pymacs-eval "pymacs" nil t)
(autoload 'pymacs-exec "pymacs" nil t)
(autoload 'pymacs-load "pymacs" nil t)
;; Initialize Rope
(require 'pymacs)
(ac-ropemacs-setup)
(pymacs-load "ropemacs" "rope-")
(setq ropemacs-enable-autoimport t)
(setq  ropemacs-guess-project t)
(setq ropemacs-confirm-saving 'nil)
